### ISSUE TITLE
add warning class

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#109]
ReSpec supports `.warning` class - which is used in various specs. Would be great if we could have it as part of base (so I can remove it from ReSpec).

This is currently what we use (where ".warning-title" would map to ".marker"):  

```CSS
.warning {
    border-color: #f11;
    border-width: .2em;
    border-style: solid;
    background: #fbe9e9;
}

.warning-title:before{
    content: "⚠"; /*U+26A0 WARNING SIGN*/
    font-size: 3em;
    float: left;
    height: 100%;
    padding-right: .3em;
    vertical-align: top;
    margin-top: -0.5em;
}
```

**Comment by thierryk** [comment]
I don't think `vertical-align:top` plays a role in this rule that includes `float:left`:

```css
.warning-title:before {
    content: "⚠"; /*U+26A0 WARNING SIGN*/
    font-size: 3em;
    float: left;
    height: 100%;
    padding-right: .3em;
    vertical-align: top;
    margin-top: -0.5em;
}
```
