### ISSUE TITLE
Highlight selected bibliography citation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#141]
It would be really great if we could copy Wikipedia's behavior for when linking to an internal bibliographical citation. That is, `:target` should distinguish the selected bibliographical entry. 

For example (see 5 below): 

![screenshot 2018-01-23 17 42 30](https://user-images.githubusercontent.com/870154/35261609-06e57202-0065-11e8-8930-35bffb459957.png)

**Comment by marcoscaceres** [comment]
Some variation of the following the following could work, as both ReSpec and Bikeshed use `#references` as the id for the References section:  

```CSS
    #references dt:target, #references dt:target + dd {
      background-color: rgb(220,220,220);
    }
```
