### ISSUE TITLE
Image ratio not preserved on narrow screens

### ISSUE THREAD

**Issue by tidoust** [w3c/tr-design#156]
Initially (and incorrectly) reported as a [ReSpec bug](https://github.com/w3c/respec/issues/1678).

Problem is `base.css` has the following rules for images at:
https://github.com/w3c/tr-design/blob/gh-pages/src/base.css#L562

```css
.figure img,    .sidefigure img,    figure img,
.figure object, .sidefigure object, figure object {
	max-width: 100%;
	margin: auto;
}
```

When both the `width` and `height` of an image are specified in the `<img>` tag, the `max-width` property shrinks the width of an image as needed, but doesn't touch the height. The image ratio breaks when that happens, see examples reported in the ReSpec bug.

Adding `height: auto;` to `base.css` would fix the issue. Not sure if that can create side effects.
