### ISSUE TITLE
Heading mark-up in notes

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#175]
This was originally [filed on ReSpec](https://github.com/w3c/respec/issues/1752) by @aardrian... but I feel we need to have a larger discussion.  

The following is a copy/paste from @aardrian's bug linked to above. 

## Description of problem

It is common practice for developers to view-source on pages for guidance on how patterns are coded, or just to take code as-is for their own use. There is HTML in the WAI-ARIA Authoring Practices 1.1 that I feel should be adjusted to better follow the principles of ARIA and best practices.

The headings in the _Notes_ throughout the document are not coded with `<h#>`, but instead rely on ARIA attributes to convey their structure. Eg:

```html
<div class="note">
 <div role="heading" class="note-title marker" id="h-note-10" aria-level="6">
  <span>Note</span>
 </div>
 […]
</div>
```

A screen shot showing an example of a note on the page.

![All-caps green text in a light green box.](https://user-images.githubusercontent.com/1376607/42537145-1036109c-8462-11e8-88b9-3b654791a67d.png)

While this does not go against [2.1 No ARIA is better than Bad ARIA](https://www.w3.org/TR/wai-aria-practices-1.1/#no_aria_better_bad_aria) as outlined in this document (because it is not incorrect), it is counter to [2.1 First Rule of ARIA Use](https://www.w3.org/TR/using-aria/#rule1). In particular, I do not believe "visual design constraints rule out the use of a particular native element" in this case.

Suggest replacing each of the `<div>`-as-heading instances with the following, as appropriate for the heading level:

```html
<h4 class="note-title marker">Note</h4>
<h5 class="note-title marker">Note</h5>
<h6 class="note-title marker">Note</h6>
```

The following CSS will allow the headings to look the same as the current `<div>`-as-heading instances:

```css
.note h4, .note h5, .note h6 {
    margin: 0;
    padding-right: 1em; /* or make div.note-title not specific to div */
    min-width: 7.5em; /* or make div.note-title not specific to div */
    font-weight: normal; /* for the h4 */
    font-style: normal; /* for the h5 */
}
```

Note: this is carried over from [github.com/w3c/aria-practices/issues/761](https://github.com/w3c/aria-practices/issues/761).

cc @awkawk
